repos:
  # Python code style check and auto-fix
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8    # Ruff version
    hooks:
      - id: ruff
        args: [--fix]          # Automatically fix common issues
      - id: ruff-format        # Formatting check (equivalent to Black)

  # Notebook code style check and auto-fix
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.8.5
    hooks:
      - id: nbqa-ruff
        args: [--fix]          # Automatically fix issues reported by Ruff in Notebooks
      - id: nbqa-ruff-format   # Notebook code formatting
