repos:
  # --- Python ---
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        name: ruff (py files)
        args: [--output-format=github]
      - id: ruff-format
        name: ruff format (py files, check only)
        args: [--check]

  # --- Notebooks: using nbQA ---
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.1
    hooks:
      - id: nbqa-ruff
        name: nbqa ruff (ipynb code cells)
        args: [--output-format=github]

  # --- misc ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
