[tool.ruff]
src = ["."]
line-length = 140
indent-width = 4
target-version = "py310"

[tool.ruff.lint]
select = ["E", "W", "F"]
ignore = ["C90", "E117", "E231", "E226"]
preview = true



[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.nbqa]
addopts = ["--line-length=140"]
