[tool.ruff]
src = ["."]
line-length = 120
indent-width = 4
target-version = "py310"

[tool.ruff.lint]
select = ["E", "W", "F", "I"]
ignore = ["C90"]
preview = true



[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.nbqa]
addopts = ["--line-length=120"]
